name: build

on: [push]

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v1
    - uses: warrenbuckley/Setup-Nuget@v1
    - run: nuget restore ./Sample5/CSharpClass.sln
    - uses: warrenbuckley/Setup-MSBuild@v1
    - run: MSBuild.exe ./Sample5/CSharpClass.sln -p:Configuration=Release
      timeout-minutes: 5
